/*
 * This source file was generated by the Gradle 'init' task
 */
package kr.butgo;

import org.junit.jupiter.api.Test;

import java.sql.SQLException;

class AppTest {
    @Test void appHasAGreeting() throws SQLException, ClassNotFoundException {
        App classUnderTest = new App();
    }
}
